[buildPlans.lj-iosevka-term]
family = "LJ's Iosevka Term"
spacing = "term"
serifs = "sans"
noCvSss = false
exportGlyphNames = true

[buildPlans.lj-iosevka-term.namingOverride]
copyright = 'Copyright 2015-{{currentYear}}, Renzhi Li (aka. Belleve Invis, belleve@typeof.net). Customization by Jason Yip'
manufacturer = 'Belleve Invis (original font), Jason Yip (customization)'
designer = 'Belleve Invis (original font), Jason Yip (customization)'
urlVendor = 'https://github.com/jasyip/ljs-iosevka'


[buildPlans.lj-iosevka-term.variants.design]
capital-b = "standard-unilateral-serifed"
capital-d = "more-rounded-unilateral-serifed"
capital-e = "top-left-serifed"
capital-f = "top-left-serifed"
capital-g = "toothless-rounded-serifless-capped"
capital-h = "top-left-serifed"
capital-k = "straight-top-left-serifed"
capital-l = "motion-serifed"
capital-m = "hanging-motion-serifed"
capital-n = "standard-motion-serifed"
capital-p = "closed-motion-serifed"
capital-q = "crossing-baseline"
capital-r = "straight-top-left-serifed"
capital-u = "toothless-rounded-unilateral-motion-serifed"
capital-v = "straight-motion-serifed"
capital-w = "straight-motion-serifed"
capital-x = "straight-unilateral-motion-serifed"
capital-y = "straight-motion-serifed"
a = "double-storey-toothless-corner"
b = "toothless-corner-serifless"
c = "unilateral-serifed"
d = "toothless-corner-serifless"
g = "double-storey"
i = "serifed-flat-tailed"
j = "serifed"
l = "serifed-flat-tailed"
m = "short-leg-serifless"
p = "earless-corner-serifless"
q = "earless-corner-diagonal-tailed-serifless"
u = "toothless-corner-serifless"
y = "curly-turn-serifless"
long-s = "bent-hook-tailed"
eszet = "sulzbacher-tailed-middle-serifed"
lower-delta = "flat-top"
capital-gamma = "top-right-serifed"
capital-lambda = "straight-top-serifed"
lower-lambda = "straight-turn"
lower-mu = "toothless-corner-serifless"
lower-xi = "rounded"
cyrl-capital-zhe = "straight"
cyrl-zhe = "straight"
cyrl-capital-ka = "straight-top-left-serifed"
cyrl-ka = "straight-top-left-serifed"
cyrl-en = "top-left-serifed"
cyrl-capital-u = "straight-motion-serifed"
cyrl-ef = "top-serifed"
cyrl-yery = "corner-tailed"
zero = "slashed"
one = "base-flat-top-serif"
seven = "curly-serifless"
nine = "open-contour"
underscore = "above-baseline"
brace = "curly-flat-boundary"
number-sign = "upright-tall"
ampersand = "et-toothless-corner"
at = "threefold-tall"
percent = "rings-continuous-slash"
bar = "force-upright"
partial-derivative = "curly-bar"
micro-sign = "toothless-corner-serifless"
lig-ltgteq = "flat"
lig-neq = "slightly-slanted"
lig-equal-chain = "with-notch"
lig-hyphen-chain = "with-notch"
lig-double-arrow-bar = "with-notch"
lig-single-arrow-bar = "with-notch"


[buildPlans.lj-iosevka-term.ligations]
enables = [
    "center-op-trigger-equal-l",
    "ltgt-diamond-tag",
    "kern-dotty",
    "kern-bars",
    "llgg",
    "llggeq",
    "tilde-tilde-tilde",
    "plus-plus",
    "hash-hash",
]



[buildPlans.lj-iosevka-term.widths.extra-condensed]
shape = 500
menu = 5
css = "extra-condensed"

[buildPlans.lj-iosevka-term.widths.condensed]
shape = 547
menu = 6
css = "condensed"

[buildPlans.lj-iosevka-term.widths.semi-condensed]
shape = 600
menu = 7
css = "semi-condensed"

[buildPlans.lj-iosevka-term.widths.normal]
shape = 657
menu = 8
css = "normal"

[buildPlans.lj-iosevka-term.widths.semi-extended]
shape = 720
menu = 9
css = "semi-expanded"




[buildPlans.lj-iosevka-fcmono]
family = "LJ's Iosevka FontConfig Mono"
spacing = "fontconfig-mono"
serifs = "sans"
noCvSss = false
exportGlyphNames = true

[buildPlans.lj-iosevka-fcmono.namingOverride]
copyright = 'Copyright 2015-{{currentYear}}, Renzhi Li (aka. Belleve Invis, belleve@typeof.net). Customization by Jason Yip'
manufacturer = 'Belleve Invis (original font), Jason Yip (customization)'
designer = 'Belleve Invis (original font), Jason Yip (customization)'
urlVendor = 'https://github.com/jasyip/ljs-iosevka'


[buildPlans.lj-iosevka-fcmono.variants.design]
capital-b = "standard-unilateral-serifed"
capital-d = "more-rounded-unilateral-serifed"
capital-e = "top-left-serifed"
capital-f = "top-left-serifed"
capital-g = "toothless-rounded-serifless-capped"
capital-h = "top-left-serifed"
capital-k = "straight-top-left-serifed"
capital-l = "motion-serifed"
capital-m = "hanging-motion-serifed"
capital-n = "standard-motion-serifed"
capital-p = "closed-motion-serifed"
capital-q = "crossing-baseline"
capital-r = "straight-top-left-serifed"
capital-u = "toothless-rounded-unilateral-motion-serifed"
capital-v = "straight-motion-serifed"
capital-w = "straight-motion-serifed"
capital-x = "straight-unilateral-motion-serifed"
capital-y = "straight-motion-serifed"
a = "double-storey-toothless-corner"
b = "toothless-corner-serifless"
c = "unilateral-serifed"
d = "toothless-corner-serifless"
g = "double-storey"
i = "serifed-flat-tailed"
j = "serifed"
l = "serifed-flat-tailed"
m = "short-leg-serifless"
p = "earless-corner-serifless"
q = "earless-corner-diagonal-tailed-serifless"
u = "toothless-corner-serifless"
y = "curly-turn-serifless"
long-s = "bent-hook-tailed"
eszet = "sulzbacher-tailed-middle-serifed"
lower-delta = "flat-top"
capital-gamma = "top-right-serifed"
capital-lambda = "straight-top-serifed"
lower-lambda = "straight-turn"
lower-mu = "toothless-corner-serifless"
lower-xi = "rounded"
cyrl-capital-zhe = "straight"
cyrl-zhe = "straight"
cyrl-capital-ka = "straight-top-left-serifed"
cyrl-ka = "straight-top-left-serifed"
cyrl-en = "top-left-serifed"
cyrl-capital-u = "straight-motion-serifed"
cyrl-ef = "top-serifed"
cyrl-yery = "corner-tailed"
zero = "slashed"
one = "base-flat-top-serif"
seven = "curly-serifless"
nine = "open-contour"
underscore = "above-baseline"
brace = "curly-flat-boundary"
number-sign = "upright-tall"
ampersand = "et-toothless-corner"
at = "threefold-tall"
percent = "rings-continuous-slash"
bar = "force-upright"
partial-derivative = "curly-bar"
micro-sign = "toothless-corner-serifless"
lig-ltgteq = "flat"
lig-neq = "slightly-slanted"
lig-equal-chain = "with-notch"
lig-hyphen-chain = "with-notch"
lig-double-arrow-bar = "with-notch"
lig-single-arrow-bar = "with-notch"

[buildPlans.lj-iosevka-fcmono.ligations]
enables = [
    "center-op-trigger-equal-l",
    "ltgt-diamond-tag",
    "kern-dotty",
    "kern-bars",
    "llgg",
    "llggeq",
    "tilde-tilde-tilde",
    "plus-plus",
    "hash-hash",
]



[buildPlans.lj-iosevka-fcmono.widths.extra-condensed]
shape = 500
menu = 5
css = "extra-condensed"

[buildPlans.lj-iosevka-fcmono.widths.condensed]
shape = 547
menu = 6
css = "condensed"

[buildPlans.lj-iosevka-fcmono.widths.semi-condensed]
shape = 600
menu = 7
css = "semi-condensed"

[buildPlans.lj-iosevka-fcmono.widths.normal]
shape = 657
menu = 8
css = "normal"

[buildPlans.lj-iosevka-fcmono.widths.semi-extended]
shape = 720
menu = 9
css = "semi-expanded"








[buildPlans.lj-iosevka-aile]
family = "LJ's Iosevka Aile"
spacing = "quasi-proportional"
serifs = "sans"
noCvSss = false
exportGlyphNames = true

[buildPlans.lj-iosevka-aile.namingOverride]
copyright = 'Copyright 2015-{{currentYear}}, Renzhi Li (aka. Belleve Invis, belleve@typeof.net). Customization by Jason Yip'
manufacturer = 'Belleve Invis (original font), Jason Yip (customization)'
designer = 'Belleve Invis (original font), Jason Yip (customization)'
urlVendor = 'https://github.com/jasyip/ljs-iosevka'


[buildPlans.lj-iosevka-aile.variants.design]
capital-d = "more-rounded-serifless"
capital-g = "toothless-rounded-serifless-hooked"
capital-q = "crossing-baseline"
c = "unilateral-serifed"
g = "double-storey"
i = "serifed-flat-tailed"
l = "serifed-flat-tailed"
m = "short-leg-serifless"
q = "tailed-serifless"
y = "curly-turn-serifless"
long-s = "bent-hook-tailed"
eszet = "sulzbacher-tailed-serifless"
lower-delta = "flat-top"
cyrl-capital-zhe = "straight"
cyrl-zhe = "straight"
cyrl-yery = "corner-tailed"
zero = "slashed"
one = "base-flat-top-serif"
seven = "curly-serifless"
nine = "open-contour"
underscore = "above-baseline"
brace = "curly-flat-boundary"
ampersand = "et-tailed"
at = "threefold-tall"
dollar = "through-cap"
percent = "rings-continuous-slash"
partial-derivative = "curly-bar"
lig-ltgteq = "flat"
lig-neq = "slightly-slanted"
lig-equal-chain = "with-notch"
lig-hyphen-chain = "with-notch"
lig-double-arrow-bar = "with-notch"
lig-single-arrow-bar = "with-notch"


[buildPlans.lj-iosevka-aile.ligations]
enables = [
    "arrow-l",
    "arrow-r",
    "arrow-lr",
    "counter-arrow-l",
    "counter-arrow-r",
    "trig",
    "eqeqeq",
    "eqslasheq",
    "ltgt-diamond-tag",
    "kern-dotty",
    "kern-bars",
    "logic",
    "llgg",
    "llggeq",
    "brace-bar",
    "brack-bar",
    "tilde-tilde",
    "minus-minus-minus",
    "plus-plus",
    "underscore-underscore",
    "hash-hash",
]


[buildPlans.lj-iosevka-aile.widths.normal]
shape = 500
menu = 5
css = "normal"

[buildPlans.lj-iosevka-aile.widths.semi-extended]
shape = 547
menu = 6
css = "semi-expanded"

[buildPlans.lj-iosevka-aile.widths.extended]
shape = 600
menu = 7
css = "expanded"

[buildPlans.lj-iosevka-aile.widths.extra-extended]
shape = 657
menu = 8
css = "extra-expanded"

[buildPlans.lj-iosevka-aile.widths.ultra-extended]
shape = 720
menu = 9
css = "ultra-expanded"








[buildPlans.lj-iosevka-etoile]
family = "LJ's Iosevka Etoile"
spacing = "quasi-proportional"
serifs = "slab"
noCvSss = false
exportGlyphNames = true

[buildPlans.lj-iosevka-etoile.namingOverride]
copyright = 'Copyright 2015-{{currentYear}}, Renzhi Li (aka. Belleve Invis, belleve@typeof.net). Customization by Jason Yip'
manufacturer = 'Belleve Invis (original font), Jason Yip (customization)'
designer = 'Belleve Invis (original font), Jason Yip (customization)'
urlVendor = 'https://github.com/jasyip/ljs-iosevka'

[buildPlans.lj-iosevka-etoile.variants.design]
capital-a = "straight-tri-serifed"
capital-d = "more-rounded-bilateral-serifed"
capital-j = "serifed-both-sides"
capital-q = "crossing-baseline"
g = "double-storey"
i = "serifed-asymmetric"
l = "serifed-asymmetric"
m = "short-leg-serifed"
q = "tailed-motion-serifed"
u = "tailed-motion-serifed"
y = "curly-turn-serifed"
long-s = "bent-hook-tailed-middle-serifed"
eszet = "sulzbacher-tailed-middle-serifed"
lower-delta = "flat-top"
capital-lambda = "straight-tri-serifed"
cyrl-capital-zhe = "curly"
cyrl-zhe = "curly"
zero = "slashed"
one = "base-flat-top-serif"
seven = "curly-serifed"
nine = "open-contour"
underscore = "above-baseline"
brace = "curly-flat-boundary"
ampersand = "et-toothed"
at = "threefold-tall"
dollar = "through-cap"
percent = "rings-continuous-slash"
question = "corner"
partial-derivative = "curly-bar"
lig-ltgteq = "flat"
lig-neq = "slightly-slanted"
lig-equal-chain = "with-notch"
lig-hyphen-chain = "with-notch"
lig-double-arrow-bar = "with-notch"
lig-single-arrow-bar = "with-notch"

[buildPlans.lj-iosevka-etoile.ligations]
enables = [
    "arrow-l",
    "arrow-r",
    "arrow-lr",
    "counter-arrow-l",
    "counter-arrow-r",
    "trig",
    "eqeqeq",
    "eqslasheq",
    "ltgt-diamond-tag",
    "kern-dotty",
    "kern-bars",
    "logic",
    "llgg",
    "llggeq",
    "brace-bar",
    "brack-bar",
    "tilde-tilde",
    "minus-minus-minus",
    "plus-plus",
    "underscore-underscore",
    "hash-hash",
]





[buildPlans.lj-iosevka-etoile.widths.normal]
shape = 500
menu = 5
css = "normal"

[buildPlans.lj-iosevka-etoile.widths.semi-extended]
shape = 547
menu = 6
css = "semi-expanded"

[buildPlans.lj-iosevka-etoile.widths.extended]
shape = 600
menu = 7
css = "expanded"

[buildPlans.lj-iosevka-etoile.widths.extra-extended]
shape = 657
menu = 8
css = "extra-expanded"

[buildPlans.lj-iosevka-etoile.widths.ultra-extended]
shape = 720
menu = 9
css = "ultra-expanded"
